export default {
  GET_WEATHER_INFORMATION: "GET_WEATHER_INFORMATION",
  SAVE_WEATHER_INFORMATION: "SAVE_WEATHER_INFORMATION",
  SET_WEATHER_ERROR: "SET_WEATHER_ERROR",
  GET_ACTUAL_LOCATION: "GET_ACTUAL_LOCATION",
  SET_ACTUAL_LOCATION: "SET_ACTUAL_LOCATION",
  SET_ACTUAL_CITY: "SET_ACTUAL_CITY",
};
